export const foodApi = [
  {
    id: "00",
    category: "Top Sellers",
    data: [
      {
        id: "01",
        name: "Poundo Yam",
        price: "350",
        desc: "Chunks of cooked white yam pounded together until smooth and dished in balls. Very similar to mashed potatoes. Best served with Local Nigerian soup of choice",
        src: "https://dl.dropboxusercontent.com/scl/fi/mrr3wfrku06l4ilhd3y5l/poundoyam.jpg?rlkey=hq718puuij9lzs5m9cixn1p2g&dl=0",
      },
      {
        id: "02",
        name: "Jollof Rice",
        price: "900",
        desc: "Long grain rice stewed with seasoned tomato sauce and served with protein of choice",
        src: "https://dl.dropboxusercontent.com/scl/fi/luvwhe05d4w8p0aj2bb26/jollofrice.jpg?rlkey=g0sffbrrc7dxq66xq1sytq2dd&dl=0",
      },
      {
        id: "03",
        name: "Jollof Rice/Chicken Combo",
        price: "1,750",
        desc: "Jollof Rice, Chicken, Water and free take away pack",
        src: "https://dl.dropboxusercontent.com/scl/fi/j29840e4ve3hancqcau7w/jollofchicken.jpg?rlkey=eymzjpryqn7mpodw9c83mrnht&dl=0",
      },
    ],
  },

  {
    id: "10",
    category: "Rice",
    data: [
      {
        id: "11",
        name: "Jollof Rice/Chicken Combo",
        price: "1,750",
        desc: "Jollof Rice, Chicken, Water and free take away pack",
        src: "https://dl.dropboxusercontent.com/scl/fi/j29840e4ve3hancqcau7w/jollofchicken.jpg?rlkey=eymzjpryqn7mpodw9c83mrnht&dl=0",
      },
      {
        id: "12",
        name: "Fried Rice/Chicken Combo",
        price: "1750",
        desc: "Fried Rice, Chicken, Water and free take away pack",
        src: "https://images2.imgbox.com/57/a4/RsSCwJZ9_o.jpg",
      },
      {
        id: "13",
        name: "Jollof Rice/Fish Combo",
        price: "1,650",
        desc: "Jollof Rice Titus Fish, Water and free take away pack",
        src: "https://dl.dropboxusercontent.com/scl/fi/yc7qhk9j948e1skzbjpev/jolloffish.jpg?rlkey=t7s4ntq8r69tavlvemi12thie&dl=0",
      },
      {
        id: "14",
        name: "Fried Rice/Fish Combo",
        price: "1,650",
        desc: "Fried Rice, Titus Fish, Water and free take away pack",
        src: "https://dl.dropboxusercontent.com/scl/fi/s0v0fzo039vy2hbqa2pjh/friedricefish.jpg?rlkey=8thj6dluw9yk48j62b3c55e1u&dl=0",
      },
      {
        id: "15",
        name: "Ofada",
        price: "1,400",
        desc: "Nigerian grown plain small grain rice served separately with pepper sauce to compliment.",
        src: "https://dl.dropboxusercontent.com/scl/fi/uq5rps03bbfkzixf947n3/ofada.jpg?rlkey=dajg9eg8qhz0ahwus27zihgak&dl=0",
      },
      {
        id: "16",
        name: "Jollof Rice",
        price: "900",
        desc: "Long grain rice stewed with seasoned tomato sauce and served with protein of choice",
        src: "https://dl.dropboxusercontent.com/scl/fi/luvwhe05d4w8p0aj2bb26/jollofrice.jpg?rlkey=g0sffbrrc7dxq66xq1sytq2dd&dl=0",
      },
      {
        id: "17",
        name: "Fried Rice",
        price: "900",
        desc: "Long grain rice stewed with seasoned tomato sauce and served with protein of choice",
        src: "https://dl.dropboxusercontent.com/scl/fi/vmltsdo88foqv88xbd5f8/friedrice.jpg?rlkey=hufipe4g9o0jgu1gxpbqksa8o&dl=0",
      },
      {
        id: "18",
        name: "White Rice",
        price: "750",
        desc: "Long grain white rice steamed / boiled",
        src: "https://dl.dropboxusercontent.com/scl/fi/n7hoepeimqtlykqg5akeq/whiterice.jpg?rlkey=fzyoq9omx363xtf1mwga962k1&dl=0",
      },
    ],
  },

  {
    id: "20",
    category: "Soups",
    data: [
      {
        id: "21",
        name: "Afang Soup",
        price: "1,200",
        desc: "Local Nigerian soup made from afang leaves",
        src: "https://dl.dropboxusercontent.com/scl/fi/5fl2dhkn7a13abcujuno2/afangsoup.jpg?rlkey=q1q0fvoxgwjc0dk4fxxmgv3dq&dl=0",
      },
      {
        id: "22",
        name: "Egusi Soup",
        price: "1,000",
        desc: "Local Nigerian soup made from melon seeds and other ingredients like red palm oil, African crayfish, meats and fish, seasoning, hot pepper and some form of leafy greens.",
        src: "https://dl.dropboxusercontent.com/scl/fi/fym00mngfi9wu41rbihwk/Egusisoup.jpg?rlkey=lyp2axxx81b87chpde4ot7yeb&dl=0",
      },
      {
        id: "23",
        name: "Edika Ikong Soup",
        price: "800",
        desc: "A nutritious combination of fresh leafy vegetables, dried fish and assorted meat",
        src: "https://dl.dropboxusercontent.com/scl/fi/sm8g33v6776m23fq7hb57/edikaikongsoup.jpg?rlkey=ge1yeoxjd21ij4qo5g02jrqtx&dl=0",
      },
      {
        id: "24",
        name: "Okra Soup",
        price: "800",
        desc: "Local soup made of okra, palm oil, fish, crayfish, pepper, salt, onion, vegetable and seasoning cubes",
        src: "https://dl.dropboxusercontent.com/scl/fi/8tcout6usm98a2dp8yqwd/okra.jpg?rlkey=6xmzfv1w57ozcz6jerw46tebt&dl=0",
      },
    ],
  },

  {
    id: "30",
    category: "Pasta",
    data: [
      {
        id: "31",
        name: "Jollof Spaghetti/Chicken Combo",
        price: "1,750",
        desc: "Jollof Spaghetti, Chicken, Water and free take away pack",
        src: "https://dl.dropboxusercontent.com/scl/fi/2vzc2m6ilywq7whm91xud/jollofpastachicken.jpg?rlkey=x6l7c14exz49cwn36a8svjmwk&dl=0",
      },
      {
        id: "32",
        name: "Jollof Spaghetti/Fish Combo",
        price: "1650",
        desc: "Jollof Spaghetti, Titus Fish, Water and free take away pack",
        src: "https://dl.dropboxusercontent.com/scl/fi/vrwucr229fopa9lyf4bn0/jollofpastafish.jpg?rlkey=2f0urz9tdh978au2qpgkcm55u&dl=0",
      },
      {
        id: "33",
        name: "Spaghetti Jollof",
        price: "800",
        desc: "Plain spaghetti stewed with seasoned tomato sauce, garnished with vegetables and served with protein of choice",
        src: "https://dl.dropboxusercontent.com/scl/fi/o049wfuzvmm818spvkh3h/spaghettijollof.jpg?rlkey=nuinxy5107jkn4zdczi7stmax&dl=0",
      },
    ],
  },

  {
    id: "40",
    category: "Side",
    data: [
      {
        id: "41",
        name: "Moi Moi",
        price: "700",
        desc: "Steamed bean pudding made from a mixture of washed and peeled black-eyed beans, onions and fresh ground red peppers.",
        src: "https://dl.dropboxusercontent.com/scl/fi/cskvj2jzib2mrrfi2hgqj/moimoi.jpg?rlkey=923d39poail3hjcpsasiwp1bl&dl=0",
      },
      {
        id: "42",
        name: "Fried Plantain",
        price: "600",
        desc: "Chopped/diced plantain strips fried in oil",
        src: "https://dl.dropboxusercontent.com/scl/fi/3krn0h6mw2u0u1c77fupd/friedplantain.jpg?rlkey=kbiriuq8mcduuh1evgs1e5b13&dl=0",
      },
      {
        id: "43",
        name: "Coleslaw",
        price: "550",
        desc: "Finely shredded raw cabbage with a salad dressing",
        src: "https://dl.dropboxusercontent.com/scl/fi/kxlguxzc5mmm9gptz5f1l/coleslaw.jpg?rlkey=mv849leugvcoegugxpprnyll4&dl=0",
      },
    ],
  },

  {
    id: "50",
    category: "Swallow",
    data: [
      {
        id: "51",
        name: "Poundo Yam",
        price: "350",
        desc: "Chunks of cooked white yam pounded together until smooth and dished in balls. Very similar to mashed potatoes. Best served with Local Nigerian soup of choice",
        src: "https://dl.dropboxusercontent.com/scl/fi/mrr3wfrku06l4ilhd3y5l/poundoyam.jpg?rlkey=hq718puuij9lzs5m9cixn1p2g&dl=0",
      },
      {
        id: "52",
        name: "Semo",
        price: "350",
        desc: "Dough made from processed cassava, corn and/wheat",
        src: "https://dl.dropboxusercontent.com/scl/fi/c2i70yabxbwt23y5jlkyx/semo.jpg?rlkey=ljezas3b5k4uwg2ttjiuoatyn&dl=0",
      },
      {
        id: "53",
        name: "Eba",
        price: "350",
        desc: "Made with fried cassava called garri and hot boiling water to form a smooth stiff dough. Best served with Local Nigerian soup of choice",
        src: "https://dl.dropboxusercontent.com/scl/fi/oics0edleqj1f1u6hlldg/eba.jpg?rlkey=wg7zdi08lmn648n9yxmjhdkqj&dl=0",
      },
    ],
  },

  {
    id: "60",
    category: "Protien",
    data: [
      {
        id: "61",
        name: "Turkey",
        price: "2000",
        desc: "Fried turkey wing",
        src: "https://dl.dropboxusercontent.com/scl/fi/8o7j7h8tlpfmutcc3xue4/Turkey.jpg?rlkey=ep2n3lc2cq2jdp0asuuytsee5&dl=0",
      },
      {
        id: "62",
        name: "Asun",
        price: "2000",
        desc: "Goat meat, scotch bonnet pepper, curry powder, green bell pepper, ginger",
        src: "https://dl.dropboxusercontent.com/scl/fi/u61fuli8otfkoyxo0rqf8/Asun.jpg?rlkey=hg6u6kkooea4h466bvgwq04p2&dl=0",
      },
      {
        id: "63",
        name: "Croaker Fish",
        price: "1200",
        desc: "Deliciously cooked croaker fish",
        src: "https://dl.dropboxusercontent.com/scl/fi/evcyvvj0lyj6uywlw9bn0/croakerfish.jpg?rlkey=633idz0llmeo17uo57dmrpz4e&dl=0",
      },
      {
        id: "64",
        name: "Chicken",
        price: "1000",
        desc: "Fried chicken",
        src: "https://dl.dropboxusercontent.com/scl/fi/al2tuh8k6wb83g53r13x0/chicken.jpg?rlkey=9gu6su4vk75j5fob5ic9oroc8&dl=0",
      },
      {
        id: "65",
        name: "Titus Fish",
        price: "800",
        desc: "Deliciously cooked titus fish",
        src: "https://dl.dropboxusercontent.com/scl/fi/fsqdv3gm35iqkky5bekca/titusfish.jpg?rlkey=loxvzdz4i82ncyvjscwl098l8&dl=0",
      },
      {
        id: "66",
        name: "Beef",
        price: "500",
        desc: "Beef stewed in hot pepper and onion mix",
        src: "https://dl.dropboxusercontent.com/scl/fi/40ml57czn12yulq0jywfx/beef.jpg?rlkey=4efh5khrwhwr0flefpda6kf7y&dl=0",
      },
      {
        id: "67",
        name: "Pomo",
        price: "500",
        desc: "Deliciously cooked cow skin",
        src: "https://dl.dropboxusercontent.com/scl/fi/7wa2c1zjnfm8c8r998bkf/pomo.jpg?rlkey=bvqjy6dkkpg7t5ykz627s0vii&dl=0",
      },
      {
        id: "68",
        name: "Assorted",
        price: "400",
        desc: "Sumptuous variety of well seasoned meat",
        src: "https://dl.dropboxusercontent.com/scl/fi/qsp8658983jktfh4yvaot/assorted.jpg?rlkey=uaxxwlcyelsqb8it5iiyfvil3&dl=0",
      },
    ],
  },

  {
    id: "70",
    category: "Soft Drinks",
    data: [
      {
        id: "71",
        name: "Red Bull",
        price: "1500",
        desc: "Energy drink",
        src: "https://dl.dropboxusercontent.com/scl/fi/imetp6h2fm3fpfoi4hnzm/redbull.jpg?rlkey=1ly5ax6lqrpipmpf7mf5zt1lv&dl=0",
      },
      {
        id: "72",
        name: "Maltina",
        price: "500",
        desc: "Warm and cold smooth, nourishing malt drink",
        src: "https://dl.dropboxusercontent.com/scl/fi/vs2y0snrqg9ec7fuvlvza/maltina.jpg?rlkey=3pu6rytiac2s7k0pdz43qgcja&dl=0",
      },
      {
        id: "73",
        name: "Schweppes Chapman",
        price: "500",
        desc: "Carbonated soft drink",
        src: "https://dl.dropboxusercontent.com/scl/fi/k5wbp2k2drcru25empczr/schweppes.jpg?rlkey=jbxjwpqf6yv9iioovf6h1k4gn&dl=0",
      },
      {
        id: "74",
        name: "Pulpy Orange Juice",
        price: "400",
        desc: "Fruit juice",
        src: "https://dl.dropboxusercontent.com/scl/fi/xzfy6gjngc6tmrrwdszwb/pulpy.jpg?rlkey=96w05l3hq84iaoidl53d54wo7&dl=0",
      },
      {
        id: "75",
        name: "Coca-Cola",
        price: "380",
        desc: "Carbonated soft drink",
        src: "https://dl.dropboxusercontent.com/scl/fi/74kvcg663c4y44lq2sv1z/cocacola.jpg?rlkey=8c9q1j8x4mal36to68xqt7fxl&dl=0",
      },
      {
        id: "76",
        name: "Fanta",
        price: "380",
        desc: "Carbonated soft drink",
        src: "https://dl.dropboxusercontent.com/scl/fi/88ef2x44f188jc61bmfl9/fanta.jpg?rlkey=s79f18rc9ga6vu3ojahmtvuoe&dl=0",
      },
      {
        id: "77",
        name: "Sprite",
        price: "380",
        desc: "Carbonated soft drink",
        src: "https://dl.dropboxusercontent.com/scl/fi/bgy8rozw5y0gstqj5w1vg/sprite.jpg?rlkey=pm6tocxubopd8ew4fduz1rggo&dl=0",
      },
      {
        id: "78",
        name: "Bottle Water",
        price: "200",
        desc: "Cold and warm drink",
        src: "https://dl.dropboxusercontent.com/scl/fi/307as2dwlebct4h4k6vc1/bottlewater.jpg?rlkey=9f38q87cr8ilnebblrr24p5ql&dl=0",
      },
    ],
  },
];
